version: 2
jobs:

  # pre-build stage
  prebuild:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout

      # static analysis
      - run: lein with-profile prebuild ancient
      - run: lein with-profile prebuild bikeshed -v -x development,production
      - run: lein with-profile prebuild cljfmt check
      - run: lein with-profile prebuild eastwood '{:namespaces [:source-paths] :exclude-linters [:redefd-vars]}'
      - run: lein with-profile prebuild kibit

      # unit testing
      - run: lein with-profile prebuild unit
      - run: lein with-profile prebuild cloverage --fail-threshold 0 --codecov
      - run:
          command: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
          when: always

  # build stage
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout

      # heroku deployment
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

      # smoke test
      # TBD

      # functional testing
      # TBD

workflows:
  version: 2

  # main pipeline
  pipeline:
    jobs:
      - prebuild
      - build:
	  requires:
	    - prebuild
